/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/agregar_venta': RouteRecordInfo<'/agregar_venta', '/agregar_venta', Record<never, never>, Record<never, never>>,
    '/categorias_productos': RouteRecordInfo<'/categorias_productos', '/categorias_productos', Record<never, never>, Record<never, never>>,
    '/clientes': RouteRecordInfo<'/clientes', '/clientes', Record<never, never>, Record<never, never>>,
    '/detalle_venta': RouteRecordInfo<'/detalle_venta', '/detalle_venta', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/proveedores': RouteRecordInfo<'/proveedores', '/proveedores', Record<never, never>, Record<never, never>>,
    '/usuarios': RouteRecordInfo<'/usuarios', '/usuarios', Record<never, never>, Record<never, never>>,
    '/venta': RouteRecordInfo<'/venta', '/venta', Record<never, never>, Record<never, never>>,
  }
}
